version: '3.7'
services:
  db:
    image: epa_db
    build:
      context: .
    networks:
      wqp:
        ipv4_address: ${DB_IPV4}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${EPA_DATABASE_NAME}
    ports:
      - ${DB_PORT}:5432
    container_name: ${EPA_DATABASE_ADDRESS}

  liquibase:
    image: epa_liquibase
    build:
      context: ./liquibase
      args:
        - LIQUIBASE_VERSION=${LIQUIBASE_VERSION}
        - A_JDBC_JAR=${JDBC_JAR}
    networks:
      wqp:
        ipv4_address: ${LIQUIBASE_IPV4}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - EPA_DATABASE_ADDRESS=${EPA_DATABASE_ADDRESS}
      - EPA_DATABASE_NAME=${EPA_DATABASE_NAME}
      - EPA_DB_OWNER_USERNAME=${EPA_DB_OWNER_USERNAME}
      - EPA_DB_OWNER_PASSWORD=${EPA_DB_OWNER_PASSWORD}
      - EPA_SCHEMA_OWNER_USERNAME=${EPA_SCHEMA_OWNER_USERNAME}
      - EPA_SCHEMA_OWNER_PASSWORD=${EPA_SCHEMA_OWNER_PASSWORD}
      - WQX_SCHEMA_NAME=${WQX_SCHEMA_NAME}
      - WQX_DUMP_SCHEMA_NAME=${WQX_DUMP_SCHEMA_NAME}
      - STORETW_SCHEMA_NAME=${STORETW_SCHEMA_NAME}
      - STORETW_DUMP_SCHEMA_NAME=${STORETW_DUMP_SCHEMA_NAME}
      - NWIS_SCHEMA_NAME=${NWIS_SCHEMA_NAME}
      - WQP_SCHEMA_NAME=${WQP_SCHEMA_NAME}
      - WQP_SCHEMA_OWNER_USERNAME=${WQP_SCHEMA_OWNER_USERNAME}
      - WQP_SCHEMA_OWNER_PASSWORD=${WQP_SCHEMA_OWNER_PASSWORD}
      - CONTEXTS=${CONTEXTS}
    volumes:
      - ./liquibase/changeLogs:/home/java/workspace/epa
      - ./liquibase/scripts:/docker-entrypoint-initdb.d
    container_name: epa_liquibase

networks:
  wqp:
    external:
      name: ${LOCAL_NETWORK_NAME}
